[package]
name = "mesh_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tobj = "3.2.3"
glutin = "0.29.1"
gl = "0.14.0"
thiserror = "1.0"
image = "*"
obj-rs = "0.7"
